# implicit rules

CC_NAME = \033[0;1;33mCC\033[0m
LD_NAME = \033[0;1;36mLD\033[0m

%.o:		%.c
		@echo -e "\t$(CC_NAME)   $(DIR)$<"
		@$(CC) $(CFLAGS) -c -o $@ $<

ifdef __DO_STATIC__
LINKAGE = -static
else
LINKAGE =
endif
